--
-- Script was generated by Devart dbForge Studio 2019 for SQL Server, Version 5.7.99.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 6/30/2022 8:40:06 PM
-- Server version: 15.00.2000
-- Please backup your database before running this script
--

USE brad_fabrica
GO

IF DB_NAME() <> N'brad_fabrica' SET NOEXEC ON
GO

--
-- Start Transaction
--
BEGIN TRANSACTION
GO

--
-- Create column [validado] on table [dbo].[BaseOrigen]
--
ALTER TABLE dbo.BaseOrigen
  ADD validado int NULL DEFAULT 0
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Commit Transaction
--
IF @@TRANCOUNT>0 COMMIT TRANSACTION
GO

--
-- Set NOEXEC to off
--
SET NOEXEC OFF
GO